force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ELN-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>This is a date time field which contain the detail of date and time when error occured</description>
    <inlineHelpText>Date and time when error occured.</inlineHelpText>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>This is a text area long field which stores the Complete Stack Track about the Problem</description>
    <inlineHelpText>Stores the Complete Stack Track about the Problem</inlineHelpText>
    <label>Log Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>This is a text field which store the Name of Either Apex Class or Apex Trigger</description>
    <inlineHelpText>Store The Name of Either Apex Class or Apex Trigger</inlineHelpText>
    <label>Process Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogDetailsTest.cls
@isTest
public class ErrorLogDetailsTest {

    @isTest
    static void insertLogTest() {
        Test.startTest();

        // Test inserting a new error log record
        String processName = 'Process 1';
        String details = 'Error occurred during processing';
        ErrorLogDetails.insertLog(processName, details);

        // Verify that the error log record was created
        List<Error_Log__c> logs = [SELECT Process_Name__c, Log_Date_Time__c, Log_Details__c FROM Error_Log__c WHERE Process_Name__c = :processName];
        System.assertEquals(1, logs.size());
        Error_Log__c log = logs[0];
        System.assertEquals(processName, log.Process_Name__c);
        System.assertEquals(details, log.Log_Details__c);

        Test.stopTest();
    }

}