force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>This is a date time field.</description>
    <inlineHelpText>Enter the end date and time of the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This a checkbox if the event is live.</description>
    <inlineHelpText>Is the event live?</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains name.</description>
    <inlineHelpText>Enter the name of event.</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteEventRecords.cls
public with sharing class DeleteEventRecords implements Database.Batchable<SObject>  {
    public Database.QueryLocator start(Database.BatchableContext batchContext){
        String query = 'Select id, Name__c from Event__c where Live__c = true AND End__c < LAST_N_MONTHS:2';
        return Database.getQueryLocator(query);

    } 

    public void execute(Database.BatchableContext batchContext, List<Event__c> listEvt){
        Database.delete(listEvt);
        
    }

    public void finish(Database.BatchableContext batchContext){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        mail.setSubject('Batch has been processed');
        List<String> toAddress = new List<String>();
        toAddress.add('pragam.kaistha@mirketa.com');
        mail.setToAddresses( toAddress );
        mail.setSenderDisplayName('Organizer');
        
        mail.setHtmlBody('The records have been deleted.');
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage> {mail};
        Messaging.sendEmail(emails);
    }
}