force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field of Event Organizer.</description>
    <inlineHelpText>Select the event organizer.</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organiser__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>This is a number field for the maximum number of seats.</description>
    <inlineHelpText>Enter the maximum number of seats in the event.</inlineHelpText>
    <label>Max Seats</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains name.</description>
    <inlineHelpText>Enter the name of event.</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>This is a date time field for event.</description>
    <inlineHelpText>Enter the start date and time of the event.</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/Event_Organiser__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizer</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organiser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field contains email.</description>
    <inlineHelpText>Enter your email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field contains phone number.</description>
    <inlineHelpText>Enter your phone number.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>This is a text field.</description>
    <inlineHelpText>Enter the company.</inlineHelpText>
    <label>Company</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is an email field .</description>
    <inlineHelpText>Enter your email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This is a phone field.</description>
    <inlineHelpText>Enter your phone number.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EventWebService.cls
@RestResource(urlMapping='/v1/EventWebService/')
global class EventWebService {
    @httpGet
    global static List<EventWrapper> doGetMethod(){
        List<EventWrapper> eventWrappers = new List<EventWrapper>();
        List<Event__c> events = [SELECT Name__c, Start__c, Max_Seats__c,Event_Organizer__r.Name , Event_Organizer__r.Email__c 
                                    FROM Event__c];
        for (Event__c event : events) {
            EventWrapper eventWrapper = new EventWrapper();
            eventWrapper.event = new Event__c();
            eventWrapper.event.Name__c = event.Name__c;
            eventWrapper.event.Start__c = event.Start__c;
            eventWrapper.event.Max_Seats__c = event.Max_Seats__c;
            eventWrapper.event_organizer = new Event_Organiser__c();
            eventWrapper.event_organizer.Name = event.Event_Organizer__r.Name;
            eventWrapper.event_organizer.Email__c = event.Event_Organizer__r.Email__c;
            eventWrappers.add(eventWrapper);
        }
        return eventWrappers;
    }

    @httpPost
    global static String doPostMethod(String Name, String email, String phone, String company){
        try
        {
        Speaker__c spkr= new Speaker__c(Name =Name, Email__c = email, Phone__c = phone, Company__c = company);
        insert spkr;
        return '200';
        }
        catch(Exception e){
            return '400';
        }
    }
    
    // Wrapper class for events
    global class EventWrapper {
        global Event__c event;
        global Event_Organiser__c event_organizer;
    }
}




















// @RestResource(urlMapping='/v1/EventWebService/')
// global class EventWebService {
//     @httpGet
//     global static List<Event__c> doGetMethod(){
//         List<Event__c> events = [SELECT Name__c, Start__c, Max_Seats__c,Event_Organizer__r.Name , Event_Organizer__r.Email__c FROM Event__c];
                
//         return events;
//     }

//     @httpPost
//     global static Speaker__c doPostMethod(String Name, String email, String phone, String company){
//         Speaker__c spkr= new Speaker__c(Name =Name, Email__c = email, Phone__c = phone, Company__c = company);
//     insert spkr;
//     return spkr;
//     }
// }