force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>This is a date time field.</description>
    <inlineHelpText>Enter the end date and time of the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>This is a date time field for event.</description>
    <inlineHelpText>Enter the start date and time of the event.</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is a master detail relationship.</description>
    <inlineHelpText>It is master detail relationship with Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>This is a master detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with speaker.</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerTriggerHandler.cls
public with sharing class EventSpeakerTriggerHandler {
    
    public static void duplicateSpeaker(List<Event_Speaker__c> eventSpeaker) {

        Set<Id> eventId = new Set<Id>();
        Set<Id> speakerId = new Set<Id>();
        for(Event_Speaker__c evtSpkr: eventSpeaker){
            eventId.add(evtSpkr.Speaker__c);
            speakerId.add(evtSpkr.Event__c);
        }

        Map<Id, Event__c> eventMap = new Map<Id, Event__c>([ SELECT Id, Start__c, End__c FROM Event__c WHERE Id IN :eventId ]);
        
        for (Event_Speaker__c evtSpkr : [ SELECT Id, Event__c, Speaker__c, Event__r.Start__c, Event__r.End__c  FROM Event_Speaker__c WHERE Speaker__c IN :speakerId ]) {
            Event__c evtTime = eventMap.get(evtSpkr.Event__c);
                Datetime evtTimeStart = evtTime.Start__c;
                Datetime evtTimeEnd = evtTime.End__c;
                // evtSpkr.Speaker__c == evtSpkr.Speaker__c &&
                    if ( ((evtTimeStart <= evtSpkr.Event__r.Start__c && evtTimeEnd >= evtSpkr.Event__r.End__c) || (evtTimeStart >= evtSpkr.Event__r.Start__c && evtTimeStart <= evtSpkr.Event__r.End__c) || (evtTimeEnd >= evtSpkr.Event__r.Start__c && evtTimeEnd <= evtSpkr.Event__r.End__c))) {
                        evtSpkr.Speaker__c.addError('Already booked');
                    }
                
            
        }
    }
}
    //     Map<Id,Event__c> evtDateTime= new Map<Id, Event__c>([Select id, Start__c from Event__c where id in :eventId]);
    //     List<Event_Speaker__c> spkr = [Select id, Event__c,Speaker__c,Event__r.Start__c, Event__r.End__c from Event_Speaker__c where id in :speakerId];
    //     for(Event_Speaker__c evtSpkr: eventSpeaker){
    //         Datetime evtTime = evtDateTime.get(evtSpkr.Event__r.Start__c);
    //         for(Event_Speaker__c checkEvtSpkr: spkr){
    //             if(evtSpkr.Speaker__c == checkEvtSpkr.Speaker__c &&  (evtSpkr.Event__r.Start__c >= checkEvtSpkr.Event__r.Start__c && evtSpkr.Event__r.Start__c < checkEvtSpkr.Event__r.End__c)){
    //                 evtSpkr.addError('Already Booked');
    //             }
    //         }
    //     }
    // }
// }