force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field of Event Organizer.</description>
    <inlineHelpText>Select the event organizer.</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organiser__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field for location.</description>
    <inlineHelpText>Select the location.</inlineHelpText>
    <label>Location (Address Book)</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains name.</description>
    <inlineHelpText>Enter the name of event.</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>This is a date time field for event.</description>
    <inlineHelpText>Enter the start date and time of the event.</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/Event_Organiser__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizer</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organiser__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field for location</description>
    <inlineHelpText>Select the location.</inlineHelpText>
    <label>Location (Address Book)</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Event Organizer</relationshipLabel>
    <relationshipName>Event_Organizer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is a master detail relationship.</description>
    <inlineHelpText>It is master detail relationship with Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>This is a master detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with speaker.</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Profile_URL__c.field-meta.xml
<CustomField>
    <fullName>Profile_URL__c</fullName>
    <description>This is a Url field to provide speaker profile link.</description>
    <inlineHelpText>Enter a your Url.</inlineHelpText>
    <label>Profile URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/EventSpeakerDetailsController.cls
public with sharing class EventSpeakerDetailsController {
    public String MstrId{get;set;}
    public Event__c evt{get;set;}
    public List<Event_Speaker__c> evtSpkr{get;set;}
    // public Speaker__c spkr{get;set;}
    public EventSpeakerDetailsController() {
        MstrId = ApexPages.currentPage().getParameters().get('id'); 

        evt = [SELECT Id, Name__c, Event_Organizer__r.Name, Location_Address_Book__r.Name, Start__c 
                FROM Event__c 
                WHERE id=:MstrId LIMIT 1];

        evtSpkr = [SELECT Id, Event__r.Name__c, Speaker__r.Name, Speaker__r.Profile_URL__c, Speaker__r.About_Me__c 
                    FROM Event_Speaker__c 
                    WHERE Event__c = :MstrId];

        // spkr = new Speaker__c();
    }
    // public EventSpeakerDetailsController(ApexPages.StandardController stdController) {
    //     this.evt = (Event__c)stdController.getRecord();
    // }
    public PageReference saveAsAttendee(){
        return new PageReference('/apex/AttendeeRegistration?param1='+MstrId).setRedirect(true);
    }
    
    public PageReference saveAsSpeaker(){
        return new PageReference('/apex/EventSpeaker?param1='+MstrId).setRedirect(true);
    }
}