force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is a master detail relationship.</description>
    <inlineHelpText>It is master detail relationship with Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>This is a master detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with speaker.</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerController.cls
public with sharing class EventSpeakerController {
    public Speaker__c spkr{get;set;}
    // public Event__c evt{get;set;}
    public String paramValue;
    public Boolean bool{get;set;}
    public Event_Speaker__c evtSpkr{get;set;}
    public EventSpeakerController() {
        
        paramValue = apexpages.currentpage().getparameters().get('param1');
        spkr = new Speaker__c();
        // evt = new Event__c();
        evtSpkr = new Event_Speaker__c();
        evtSpkr.Event__c = paramValue;
        if(paramValue!=null){
            bool= false;
        }
        else{
            bool = true;
        }
    
    }

    // public PageReference save(){
    //     insert spkr;
    //     evtSpkr.Speaker__c = spkr.Id;
    //     insert evtSpkr;
    //     return new PageReference('/apex/EventSpeaker').setRedirect(true);
    // }

    public void save(){
        insert spkr;
        evtSpkr.Speaker__c = spkr.Id;
        insert evtSpkr;
    }
}