force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field of Event Organizer.</description>
    <inlineHelpText>Select the event organizer.</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organiser__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>This is a number field for the maximum number of seats.</description>
    <inlineHelpText>Enter the maximum number of seats in the event.</inlineHelpText>
    <label>Max Seats</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains name.</description>
    <inlineHelpText>Enter the name of event.</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>This is a date time field for event.</description>
    <inlineHelpText>Enter the start date and time of the event.</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/Event_Organiser__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizer</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organiser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field contains email.</description>
    <inlineHelpText>Enter your email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventWebServiceTest.cls
@isTest
public with sharing class EventWebServiceTest {
    static testMethod void testGetMethod() {
        Event__c evt = new Event__c();
        Event_Organiser__c evtOrg = new Event_Organiser__c();
        evt.Name__c = 'Test Event Web Service 1';
        evt.Start__c = datetime.newInstance(2024, 9, 15, 12, 30, 0);
        evt.Max_Seats__c = 50;
        evtOrg.Name = 'Test Event Organizer Web Service 1';
        evtOrg.Email__c = 'abc@abc.com';
        insert evtOrg;
        evt.Event_Organizer__c = evtOrg.Id;
        insert evt;
        RestRequest req = new RestRequest();
        req.requestURI='/services/apexrest/v1/EventWebService/';
        req.httpMethod='Get';
        RestContext.request = req;
        Test.startTest();
        List<EventWebService.EventWrapper>  evnt = EventWebService.doGetMethod();
        Test.stopTest();
        System.assert(evnt!=null);
        System.assertEquals('Test Event Web Service 1', evnt.get(0).event.Name__c);

        
    }
    static testMethod void testPostMethod(){
        RestRequest req = new RestRequest();
        req.requestUri ='/services/apexrest/v1/EventWebService/';
        req.httpMethod = 'POST';

        RestContext.request = req;
        Test.startTest();
        String strId = EventWebService.doPostMethod('Event Organizer Web Service Test 1','p@p.com','123884245','comp');
        String strId2 = EventWebService.doPostMethod('Event Organizer Web Service Test 1','pk','123884245','comp');
        Test.stopTest();
        System.assertEquals('200', strId);
        System.assertEquals('400', strId2);
    }
}