force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field of Event Organizer.</description>
    <inlineHelpText>Select the event organizer.</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organiser__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field for location.</description>
    <inlineHelpText>Select the location.</inlineHelpText>
    <label>Location (Address Book)</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/Event_Organiser__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizer</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organiser__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field for location</description>
    <inlineHelpText>Select the location.</inlineHelpText>
    <label>Location (Address Book)</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Event Organizer</relationshipLabel>
    <relationshipName>Event_Organizer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventRegistrationController.cls
public with sharing class EventRegistrationController {

    public Event_Organiser__c evtOrganizer {get;set;}
	public Event__c evt {get;set;}
	public Location_Address_Book__c	 loc {get;set;}

	public EventRegistrationController ()
	{
		evtOrganizer = new Event_Organiser__c();
		evt = new Event__c();
		loc = new Location_Address_Book__c();
	}
	public PageReference save() 
	{
		// insert con;
        
		insert loc;
        evtOrganizer.Location_Address_Book__c = loc.Id;
        // loc = new Location_Address_Book__c();
		
		insert evtOrganizer;
        evt.Event_Organizer__c = evtOrganizer.Id;
		evt.Location_Address_Book__c = loc.Id;
        // evtOrganizer = new Event_Organiser__c();
		insert evt;
        // evt = new Event__c();
        // resetValue();
        return null;
		// return new PageReference('/apex/EventRegistration').setRedirect(true);
	}
	// public void resetValue(){
	// 	loc = new Location_Address_Book__c();
	// 	evtOrganizer = new Event_Organiser__c();
	// 	evt = new Event__c();
	// }
}