force-app/main/default/objects/Attendee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field for address.</description>
    <inlineHelpText>Select the location.</inlineHelpText>
    <label>Address</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field for location.</description>
    <inlineHelpText>Select the location.</inlineHelpText>
    <label>Location (Address Book)</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>This a master detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is a master-detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeRegistrationController.cls
public with sharing class AttendeeRegistrationController {
    public Event_Attendee__c evtAttndee{get;set;}
    public Attendee__c attndee{get;set;}
    public Location_Address_Book__c loc{get;set;}
    public String paramValue;
    public Boolean bool{get;set;}
    public AttendeeRegistrationController() {
        paramValue = apexpages.currentpage().getparameters().get('param1');
        evtAttndee = new Event_Attendee__c();
        attndee = new Attendee__c();
        loc = new Location_Address_Book__c();
        // bool =true;
        evtAttndee.Event__c = paramValue;
        // if(paramValue!=null){
        //     bool= false;
        // }
        // else{
        //     bool = true;
        // }
    
    }
    
    public void save(){
        insert loc;
        attndee.Address__c = loc.Id;
        insert attndee;
        evtAttndee.Attendee__c = attndee.Id;
        insert evtAttndee;

        evtAttndee = new Event_Attendee__c();
        attndee = new Attendee__c();
        loc = new Location_Address_Book__c();
    
    }
}