force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This is an email field.</description>
    <inlineHelpText>Enter your email id.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>This is a date time field.</description>
    <inlineHelpText>Enter the end date and time of the event</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup field of Event Organizer.</description>
    <inlineHelpText>Select the event organizer.</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organiser__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>This is a picklist field to select the event type.</description>
    <inlineHelpText>Select the event type.</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>This is a picklist field for the frequency of event.</description>
    <inlineHelpText>Select the frequency of the event.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This a checkbox if the event is live.</description>
    <inlineHelpText>Is the event live?</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>This is a number field for the maximum number of seats.</description>
    <inlineHelpText>Enter the maximum number of seats in the event.</inlineHelpText>
    <label>Max Seats</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains name.</description>
    <inlineHelpText>Enter the name of event.</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a checkbox if the event is recurring or not.</description>
    <inlineHelpText>Is te event recurring?</inlineHelpText>
    <label>Recurring?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>This is a date time field for event.</description>
    <inlineHelpText>Enter the start date and time of the event.</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>This a master detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This is a master-detail relationship.</description>
    <inlineHelpText>It is a master detail relationship with Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/Event_Organiser__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizer</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organiser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field contains email.</description>
    <inlineHelpText>Enter your email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organiser__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field contains phone number.</description>
    <inlineHelpText>Enter your phone number.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTriggerTest.cls
@isTest
private class EventAttendeeTriggerTest {
    @isTest
    static void sendEmailsTest() {
        // Setup test data
        Event_Organiser__c org = new Event_Organiser__c(
            Name = 'Test Org',
            Phone__c = '1234567890',
            Email__c = 'pragam.kaistha@mirketa.com'
        );
        insert org;
        Event__c evt = new Event__c(
            Name__c = 'Test Event',
            Event_Organizer__c = org.Id,
            Event_Type__c = 'Virtual',
            Frequency__c = 'Weekly',
            Max_Seats__c = 100,
            Recurring__c = true,
            Live__c = true,
            Start__c = System.now().addDays(1),
            End__c = System.now().addDays(3)
        );
        insert evt;
        Attendee__c att = new Attendee__c(
            Name = 'Test Attendee',
            Email__c = 'kaisthapragam@gmail.com',
            Phone__c = '1234567890'
        );
        insert att;
        Event_Attendee__c evtAtt = new Event_Attendee__c(
            Event__c = evt.Id,
            Attendee__c = att.Id
        );
        insert evtAtt;
        
        // Call the method being tested
        Test.startTest();
        EventAttendeeTriggerHandler.sendEmails(new List<Event_Attendee__c>{ evtAtt });
        Test.stopTest();
        
        // Verify that an email was sent
        System.assertEquals(1, Limits.getEmailInvocations());
    }


    // @isTest
    // static void notSendEmailsTest() {
    //     // Setup test data
    //     Event_Organiser__c org = new Event_Organiser__c(
    //         Name = 'Test Org123',
    //         Phone__c = '326915494'
    //     );
    //     insert org;
    //     Event__c evt = new Event__c(
    //         Max_Seats__c = 100,
    //         Live__c = true,
    //         Start__c = System.now().addDays(1),
    //         End__c = System.now().addDays(3)
    //     );
    //     insert evt;
    //     Attendee__c att = new Attendee__c(
    //         Name = 'Test Attendee',
    //         Phone__c = '1234656490'
    //     );
    //     insert att;
    //     Event_Attendee__c evtAtt1 = new Event_Attendee__c(
    //         Event__c = evt.Id,
    //         Attendee__c = att.Id
    //     );
    //     insert evtAtt1;
        
    //     // Call the method being tested
    //     Test.startTest();
    //     EventAttendeeTriggerHandler.sendEmails(new List<Event_Attendee__c>{ evtAtt1 });
    //     Test.stopTest();
        
    //     // Verify that an email was sent
    //     System.assertEquals(0, Limits.getEmailInvocations());
    // }
}